### ISSUE TITLE
Where is this plug in released to?

### ISSUE THREAD

**Issue by pupeno** [stevenmz/packer-maven-plugin#2]
It doesn't seem to be in Maven Central: https://search.maven.org/#search%7Cga%7C1%7Cpackr-maven-plugin

**Comment by stevenmz** [comment]
@pupeno I am now hosting all artifacts on GitHub Packages: [Here](https://github.com/stevenmz/packer-maven-plugin/packages/243440). This sidesteps the issue where I was not authorized to post to Maven Central in my organization's name.

Following that link, you can download the Jar as well as find information on how to add this project as a dependency on your projects.

Sorry it took two years to reply!

**Comment by stevenmz** [comment]
Releases now have a home!
